# Tốc độ xử lý của NumPy

Gấp 10 đến 100 lần so với Python thuần túy

In [1]:
my_list = list(range(1000000))
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 827 ms, sys: 243 ms, total: 1.07 s
Wall time: 1.27 s


In [2]:
import numpy as np
my_arr = np.arange(1000000)
%time for _ in range(10): my_arr2 = my_arr * 2


CPU times: user 25.7 ms, sys: 13 ms, total: 38.7 ms
Wall time: 39.2 ms


In [4]:
print(my_arr[1:10])
print(my_arr.shape)
print(my_arr.ndim)

[1 2 3 4 5 6 7 8 9]
(1000000,)
1


# Mảng đa chiều (N-dimensional array object)

NumPy cho phép thực hiện các phép toán trên mảng tương tự các phép toán trên số thực

In [6]:
np.random.randn(1,2)
help(np.random.randn)

Help on built-in function randn:

randn(...) method of numpy.random.mtrand.RandomState instance
    randn(d0, d1, ..., dn)
    
    Return a sample (or samples) from the "standard normal" distribution.
    
    .. note::
        This is a convenience function for users porting code from Matlab,
        and wraps `standard_normal`. That function takes a
        tuple to specify the size of the output, which is consistent with
        other NumPy functions like `numpy.zeros` and `numpy.ones`.
    
    .. note::
        New code should use the ``standard_normal`` method of a ``default_rng()``
        instance instead; please see the :ref:`random-quick-start`.
    
    If positive int_like arguments are provided, `randn` generates an array
    of shape ``(d0, d1, ..., dn)``, filled
    with random floats sampled from a univariate "normal" (Gaussian)
    distribution of mean 0 and variance 1. A single float randomly sampled
    from the distribution is returned if no argument is provided.
 

In [19]:
np.random.seed(1)
data = np.random.randn(2, 3)
data

array([[ 1.62434536, -0.61175641, -0.52817175],
       [-1.07296862,  0.86540763, -2.3015387 ]])

In [20]:
data[1,2]

-2.3015386968802827

In [21]:
data * 2

array([[ 3.24869073, -1.22351283, -1.0563435 ],
       [-2.14593724,  1.73081526, -4.60307739]])

In [22]:
data + data

array([[ 3.24869073, -1.22351283, -1.0563435 ],
       [-2.14593724,  1.73081526, -4.60307739]])

# Cách khởi tạo mảng trong NumPy

Sử dụng phương thức array() để chuyển mảng trong Python qua mảng trong NumPy

In [23]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array, the
        newly c

In [24]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [25]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]] 
arr2 = np.array(data2)
arr2


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

# Các thuộc tính của đối tượng ndarray

In [26]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [27]:
arr1.ndim

1

In [28]:
arr1.shape

(5,)

In [74]:
arr1.dtype

dtype('float64')

In [29]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [30]:
arr2.ndim

2

In [31]:
arr2.shape

(2, 4)

In [32]:
arr2.dtype

dtype('int64')

In [33]:
data2

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [34]:
# tao ndarray tu data2 voi dtype=float64
arr3 = np.array(data2, dtype=np.float64)
arr3

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

In [35]:
help(np.empty)

Help on built-in function empty in module numpy:

empty(...)
    empty(shape, dtype=float, order='C')
    
    Return a new array of given shape and type, without initializing entries.
    
    Parameters
    ----------
    shape : int or tuple of int
        Shape of the empty array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        Desired output data-type for the array, e.g, `numpy.int8`. Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of uninitialized (arbitrary) data of the given shape, dtype, and
        order.  Object arrays will be initialized to None.
    
    See Also
    --------
    empty_like : Return an empty array with shape and type of input.
    ones : Return a new array setting values to one.
    zeros : Return a new array 

In [39]:
np.empty([2, 2], dtype=np.float64)

array([[2.68156159e+154, 3.11107821e+231],
       [1.49457075e-154, 2.82463957e-309]])

# Cách khởi tạo mảng trong NumPy

Khởi tạo mảng đa chiều với các phần tử ‘0’

In [40]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [41]:
np.zeros((2, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [42]:
arr4 = np.empty((2, 3, 3))
arr4

array([[[ 2.68156159e+154, -3.11107821e+231,  4.44659081e-323],
        [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000],
        [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000]],

       [[ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000],
        [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000],
        [ 1.49457075e-154,  2.68156159e+154,  1.25593377e-308]]])

In [43]:
np.empty((2, 2), dtype=np.float64)

array([[2.68156159e+154, 3.11107821e+231],
       [1.49457075e-154, 2.82463957e-309]])

In [85]:
# type upcasting
arr3 = np.array([1, 2, 3], dtype=np.float64)
arr3

array([1., 2., 3.])

In [86]:
# type downcasting
arr3 = np.array([1.5, 2.9, 3.0], dtype=np.int64)
arr3

array([1, 2, 3])

Kiểu dữ liệu trong NumPy

In [87]:
numeric_strings = np.array(['1.25', '-9.6', '42'])

In [88]:
numeric_strings

array(['1.25', '-9.6', '42'], dtype='<U4')

In [89]:
numeric_strings1 = np.array(['1.25', '-9.6', '42'], dtype=np.string_)

In [90]:
numeric_strings1

array([b'1.25', b'-9.6', b'42'], dtype='|S4')

In [90]:
numeric_strings2 = numeric_strings1.astype(float)
numeric_strings2

array([ 1.25, -9.6 , 42.  ])

# Toán tử vecto hoá (element-wise)

NumPy cung cấp các toán tử để thực hiện các phép tính trên mảng mà không cần sử dụng các lệnh vòng lặp. Người dùng NumPy gọi đây là vector hóa (vectorization).

In [44]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]]) 
print(arr)
print(arr*arr)
print(arr-arr)
print(1/arr)

[[1. 2. 3.]
 [4. 5. 6.]]
[[ 1.  4.  9.]
 [16. 25. 36.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]


In [46]:
print(arr)
arr2 = np.array([[0., 4., 1.], [7., 2., 3.]]) 
print(arr2)
tmp = arr>arr2
tmp
tmp.dtype

[[1. 2. 3.]
 [4. 5. 6.]]
[[0. 4. 1.]
 [7. 2. 3.]]


dtype('bool')

Để thao tác với các phần tử hay các tập con trong mảng của NumPy, ta thao tác như List của Python

In [98]:
arr = np.arange(10) 
print(arr)
print(arr[5]) 
print(arr[5:-1])

[0 1 2 3 4 5 6 7 8 9]
5
[5 6 7 8]


In [53]:
data = np.random.randn(7, 4) # shape (7,4), ndim=2
print('--- data ---')
print(data)
row3 = data[1:4,:] # extract 3 hang (dim 0) co chi so 1 den 3 cua data
print('--- row3 ---')
print(row3)
col3 = data[:,1:4] # extract 3 cot (dim 1) co chi so 1 den 3 cua data
print('--- col3 ---')
print(col3)
rl23 = data[1:3,1:4] # extract 2 hang 1,2 va 3 cot 1 den 3 cua data
print('--- rl23 ---')
print(rl23)
print('--- ??? ---')
data[:,:-1]

--- data ---
[[ 0.04366899 -0.22631424  1.33145711 -0.28730786]
 [ 0.68006984 -0.3198016  -1.27255876  0.31354772]
 [ 0.50318481  1.29322588 -0.11044703 -0.61736206]
 [ 0.5627611   0.24073709  0.28066508 -0.0731127 ]
 [ 1.16033857  0.36949272  1.90465871  1.1110567 ]
 [ 0.6590498  -1.62743834  0.60231928  0.4202822 ]
 [ 0.81095167  1.04444209 -0.40087819  0.82400562]]
--- row3 ---
[[ 0.68006984 -0.3198016  -1.27255876  0.31354772]
 [ 0.50318481  1.29322588 -0.11044703 -0.61736206]
 [ 0.5627611   0.24073709  0.28066508 -0.0731127 ]]
--- col3 ---
[[-0.22631424  1.33145711 -0.28730786]
 [-0.3198016  -1.27255876  0.31354772]
 [ 1.29322588 -0.11044703 -0.61736206]
 [ 0.24073709  0.28066508 -0.0731127 ]
 [ 0.36949272  1.90465871  1.1110567 ]
 [-1.62743834  0.60231928  0.4202822 ]
 [ 1.04444209 -0.40087819  0.82400562]]
--- rl23 ---
[[-0.3198016  -1.27255876  0.31354772]
 [ 1.29322588 -0.11044703 -0.61736206]]
--- ??? ---


array([[ 0.04366899, -0.22631424,  1.33145711],
       [ 0.68006984, -0.3198016 , -1.27255876],
       [ 0.50318481,  1.29322588, -0.11044703],
       [ 0.5627611 ,  0.24073709,  0.28066508],
       [ 1.16033857,  0.36949272,  1.90465871],
       [ 0.6590498 , -1.62743834,  0.60231928],
       [ 0.81095167,  1.04444209, -0.40087819]])

Dùng mảng Boolean để tạo mảng con lấy ra từ 1 mảng khác nếu như 2 mảng có cùng chiều dài

In [54]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', ' Joe', 'Joe']) # shape (7,), ndim=1
data = np.random.randn(7, 4) # shape (7,4), ndim=2
print(names)
print('----')
print(data)
print('----')
bArr = (names=='Bob') # shape (7,), ndim=1
print(bArr)
print('----')
# tao mang moi tu mang data gom cac hang (dim 0) co chi so tuong ung voi vị tri names='Bob'
new_arr = data[bArr]
new_arr

['Bob' 'Joe' 'Will' 'Bob' 'Will' ' Joe' 'Joe']
----
[[-0.56230543  1.95487808 -1.33195167 -1.76068856]
 [-1.65072127 -0.89055558 -1.1191154   1.9560789 ]
 [-0.3264995  -1.34267579  1.11438298 -0.58652394]
 [-1.23685338  0.87583893  0.62336218 -0.43495668]
 [ 1.40754     0.12910158  1.6169496   0.50274088]
 [ 1.55880554  0.1094027  -1.2197444   2.44936865]
 [-0.54577417 -0.19883786 -0.7003985  -0.20339445]]
----
[ True False False  True False False False]
----


array([[-0.56230543,  1.95487808, -1.33195167, -1.76068856],
       [-1.23685338,  0.87583893,  0.62336218, -0.43495668]])

In [120]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob'])
data = np.random.randn(7, 4) 
print(names)
print(data)
bArr = (names=='Bob')
print(bArr)
# tao mang moi tu mang data gom cac cot (dim 1) co chi so tuong ung voi vị tri names='Bob'
new_arr = data[:,bArr]
new_arr

['Bob' 'Joe' 'Will' 'Bob']
[[ 0.19480759  1.1170717  -0.49005068 -1.00409384]
 [-0.48667153 -1.48944268  0.79132013 -1.12682358]
 [-1.7339251   0.91453725  0.96692051 -0.1037882 ]
 [-0.05424126 -0.72040116  1.7167484  -0.72562403]
 [-1.00043868  0.10577565  0.05390387 -0.11301861]
 [-0.48052778  0.67136122 -0.8586809   0.10648897]
 [ 0.635065   -0.1201173  -1.92080774 -2.3002476 ]]
[ True False False  True]


array([[ 0.19480759, -1.00409384],
       [-0.48667153, -1.12682358],
       [-1.7339251 , -0.1037882 ],
       [-0.05424126, -0.72562403],
       [-1.00043868, -0.11301861],
       [-0.48052778,  0.10648897],
       [ 0.635065  , -2.3002476 ]])

In [122]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', ' Joe', 'Joe']) # shape (7,), ndim=1
print(data)
data[names == 'Bob', 2:]

[[ 0.19480759  1.1170717  -0.49005068 -1.00409384]
 [-0.48667153 -1.48944268  0.79132013 -1.12682358]
 [-1.7339251   0.91453725  0.96692051 -0.1037882 ]
 [-0.05424126 -0.72040116  1.7167484  -0.72562403]
 [-1.00043868  0.10577565  0.05390387 -0.11301861]
 [-0.48052778  0.67136122 -0.8586809   0.10648897]
 [ 0.635065   -0.1201173  -1.92080774 -2.3002476 ]]


array([[-0.49005068, -1.00409384],
       [ 1.7167484 , -0.72562403]])

In [55]:
tmp = data[names == 'Bob', 3]
print(tmp)
print(tmp.shape)
print(tmp.ndim)

[-1.76068856 -0.43495668]
(2,)
1


In [56]:
# tuy nhien
tmp = data[names == 'Bob', 3:4]
print(tmp)
print(tmp.shape)
print(tmp.ndim)

[[-1.76068856]
 [-0.43495668]]
(2, 1)
2


In [57]:
tmp.shape

(2, 1)

In [58]:
data < 0

array([[ True, False,  True,  True],
       [ True,  True,  True, False],
       [ True,  True, False,  True],
       [ True, False, False,  True],
       [False, False, False, False],
       [False, False,  True, False],
       [ True,  True,  True,  True]])

In [59]:
print(data)
data[data<0] = 0 # gan cac phan tu < 0 bang 0
print(data)

[[-0.56230543  1.95487808 -1.33195167 -1.76068856]
 [-1.65072127 -0.89055558 -1.1191154   1.9560789 ]
 [-0.3264995  -1.34267579  1.11438298 -0.58652394]
 [-1.23685338  0.87583893  0.62336218 -0.43495668]
 [ 1.40754     0.12910158  1.6169496   0.50274088]
 [ 1.55880554  0.1094027  -1.2197444   2.44936865]
 [-0.54577417 -0.19883786 -0.7003985  -0.20339445]]
[[0.         1.95487808 0.         0.        ]
 [0.         0.         0.         1.9560789 ]
 [0.         0.         1.11438298 0.        ]
 [0.         0.87583893 0.62336218 0.        ]
 [1.40754    0.12910158 1.6169496  0.50274088]
 [1.55880554 0.1094027  0.         2.44936865]
 [0.         0.         0.         0.        ]]


# Fancy Indexing

NumPy cho phép tạo 1 mảng con theo chỉ mục cho trước

In [60]:
names = np.array(['Tuan', 'Phuong', 'Khoi', 'Hieu', 'Duy' , 'Thang', 'Duc'])
print(names)
# tao mang moi tu mang names gom cac ptu co index 0,5,4 cua dim0
print(names[[0,5,4]])

['Tuan' 'Phuong' 'Khoi' 'Hieu' 'Duy' 'Thang' 'Duc']
['Tuan' 'Thang' 'Duy']


In [61]:
data

array([[0.        , 1.95487808, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 1.9560789 ],
       [0.        , 0.        , 1.11438298, 0.        ],
       [0.        , 0.87583893, 0.62336218, 0.        ],
       [1.40754   , 0.12910158, 1.6169496 , 0.50274088],
       [1.55880554, 0.1094027 , 0.        , 2.44936865],
       [0.        , 0.        , 0.        , 0.        ]])

In [62]:
print(data)
print('----')
tmp = data[:,[3,0]] # lay ra cot 3 va cot 0
print(tmp)
print('----')
tmp.shape

[[0.         1.95487808 0.         0.        ]
 [0.         0.         0.         1.9560789 ]
 [0.         0.         1.11438298 0.        ]
 [0.         0.87583893 0.62336218 0.        ]
 [1.40754    0.12910158 1.6169496  0.50274088]
 [1.55880554 0.1094027  0.         2.44936865]
 [0.         0.         0.         0.        ]]
----
[[0.         0.        ]
 [1.9560789  0.        ]
 [0.         0.        ]
 [0.         0.        ]
 [0.50274088 1.40754   ]
 [2.44936865 1.55880554]
 [0.         0.        ]]
----


(7, 2)

In [63]:
print(data)
print('----')
tmp = data[[0,1,2,3],[0,1,2,3]] # lay ra data[0,0], data[1,1],...
print(tmp)
print('----')
tmp.shape

[[0.         1.95487808 0.         0.        ]
 [0.         0.         0.         1.9560789 ]
 [0.         0.         1.11438298 0.        ]
 [0.         0.87583893 0.62336218 0.        ]
 [1.40754    0.12910158 1.6169496  0.50274088]
 [1.55880554 0.1094027  0.         2.44936865]
 [0.         0.         0.         0.        ]]
----
[0.         0.         1.11438298 0.        ]
----


(4,)

In [68]:
# chuyen array 1x32 thanh arr 8x4
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [69]:
print(arr[[1, 5, 7, 2]]) # lay 4 hang 1,5,7,2
print()
print(arr[[1, 5, 7, 2]] [:, :]) # lay 4 hang 1,5,7,2 va tat ca cot
print(arr[[1, 5, 7, 2]] [:, [0, 3]]) # lay 4 hang 1,5,7,2 va cot 0, 3
print(arr[:,[0,3]] [[1, 5, 7, 2]]) # lay 4 hang 1,5,7,2 va cot 0, 3

[[ 4  5  6  7]
 [20 21 22 23]
 [28 29 30 31]
 [ 8  9 10 11]]

[[ 4  5  6  7]
 [20 21 22 23]
 [28 29 30 31]
 [ 8  9 10 11]]
[[ 4  7]
 [20 23]
 [28 31]
 [ 8 11]]
[[ 4  7]
 [20 23]
 [28 31]
 [ 8 11]]


In [74]:
print(arr)
print()
print(arr[[1, 5, 7, 2]])
print()
print(arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]])
print()
print(arr[[1, 5, 7, 2], [0, 3, 1, 2]])


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]

[[ 4  5  6  7]
 [20 21 22 23]
 [28 29 30 31]
 [ 8  9 10 11]]

[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]

[ 4 23 29 10]


Ma trận chuyển vị

In [200]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [201]:
arr.T

array([[ 0,  4,  8, 12, 16, 20, 24, 28],
       [ 1,  5,  9, 13, 17, 21, 25, 29],
       [ 2,  6, 10, 14, 18, 22, 26, 30],
       [ 3,  7, 11, 15, 19, 23, 27, 31]])

In [202]:
arr.transpose()

array([[ 0,  4,  8, 12, 16, 20, 24, 28],
       [ 1,  5,  9, 13, 17, 21, 25, 29],
       [ 2,  6, 10, 14, 18, 22, 26, 30],
       [ 3,  7, 11, 15, 19, 23, 27, 31]])

In [138]:
arr = np.arange(16).reshape((2, 8))
print(arr)
print('-----')
print(arr.T)
print('-----')
print(arr.transpose())
print('-----')
print(arr.swapaxes(0, 1))

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]
-----
[[ 0  8]
 [ 1  9]
 [ 2 10]
 [ 3 11]
 [ 4 12]
 [ 5 13]
 [ 6 14]
 [ 7 15]]
-----
[[ 0  8]
 [ 1  9]
 [ 2 10]
 [ 3 11]
 [ 4 12]
 [ 5 13]
 [ 6 14]
 [ 7 15]]
-----
[[ 0  8]
 [ 1  9]
 [ 2 10]
 [ 3 11]
 [ 4 12]
 [ 5 13]
 [ 6 14]
 [ 7 15]]


In [75]:
arr1 = np.arange(16).reshape((2, 8))
arr2 = np.arange(16).reshape((2, 8))
arr_sum1 = arr1 + arr2
arr_sum2 = np.add(arr1,arr2)
arr_sum1 == arr_sum2

array([[ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True]])

In [82]:
points = np.arange(-5, 5, 1)
print(points)
x, y = np.meshgrid(points, points)
z = np.sqrt(x ** 2 + y ** 2)
print(z)
help(np.meshgrid)

[-5 -4 -3 -2 -1  0  1  2  3  4]
[[7.07106781 6.40312424 5.83095189 5.38516481 5.09901951 5.
  5.09901951 5.38516481 5.83095189 6.40312424]
 [6.40312424 5.65685425 5.         4.47213595 4.12310563 4.
  4.12310563 4.47213595 5.         5.65685425]
 [5.83095189 5.         4.24264069 3.60555128 3.16227766 3.
  3.16227766 3.60555128 4.24264069 5.        ]
 [5.38516481 4.47213595 3.60555128 2.82842712 2.23606798 2.
  2.23606798 2.82842712 3.60555128 4.47213595]
 [5.09901951 4.12310563 3.16227766 2.23606798 1.41421356 1.
  1.41421356 2.23606798 3.16227766 4.12310563]
 [5.         4.         3.         2.         1.         0.
  1.         2.         3.         4.        ]
 [5.09901951 4.12310563 3.16227766 2.23606798 1.41421356 1.
  1.41421356 2.23606798 3.16227766 4.12310563]
 [5.38516481 4.47213595 3.60555128 2.82842712 2.23606798 2.
  2.23606798 2.82842712 3.60555128 4.47213595]
 [5.83095189 5.         4.24264069 3.60555128 3.16227766 3.
  3.16227766 3.60555128 4.24264069 5.        ]
 [6.4

In [83]:
help(np.sort)

Help on function sort in module numpy:

sort(a, axis=-1, kind=None, order=None)
    Return a sorted copy of an array.
    
    Parameters
    ----------
    a : array_like
        Array to be sorted.
    axis : int or None, optional
        Axis along which to sort. If None, the array is flattened before
        sorting. The default is -1, which sorts along the last axis.
    kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, optional
        Sorting algorithm. The default is 'quicksort'. Note that both 'stable'
        and 'mergesort' use timsort or radix sort under the covers and, in general,
        the actual implementation will vary with data type. The 'mergesort' option
        is retained for backwards compatibility.
    
        .. versionchanged:: 1.15.0.
           The 'stable' option was added.
    
    order : str or list of str, optional
        When `a` is an array with fields defined, this argument specifies
        which fields to compare first, second, etc.  A si

In [107]:

np.random.seed(1)
x = np.random.randn(4,3)
import copy
y = copy.deepcopy(x)
print(id(x[0]) == id(y[0]))
print(x)
print('--- in-place sorting of x ---')
print()
x.sort(0) # sap xep cac phan tu trong 1 cot tang dan (co dinh cot, thay doi hang)
print(x)
print()
x.sort(1) # sap xep cac phan tu trong 1 hang tang dan (co dinh hang, thay doi cot)
print(x)
print('--- tao cac copy cua arr y sau khi sap xep ---')
print(y)
y_cot = np.sort(y, 0)
y_hang = np.sort(y_cot, 1)
print(y_cot)
print()
print(y_hang)

True
[[ 1.62434536 -0.61175641 -0.52817175]
 [-1.07296862  0.86540763 -2.3015387 ]
 [ 1.74481176 -0.7612069   0.3190391 ]
 [-0.24937038  1.46210794 -2.06014071]]
--- in-place sorting of x ---

[[-1.07296862 -0.7612069  -2.3015387 ]
 [-0.24937038 -0.61175641 -2.06014071]
 [ 1.62434536  0.86540763 -0.52817175]
 [ 1.74481176  1.46210794  0.3190391 ]]

[[-2.3015387  -1.07296862 -0.7612069 ]
 [-2.06014071 -0.61175641 -0.24937038]
 [-0.52817175  0.86540763  1.62434536]
 [ 0.3190391   1.46210794  1.74481176]]
--- tao cac copy cua arr y sau khi sap xep ---
[[ 1.62434536 -0.61175641 -0.52817175]
 [-1.07296862  0.86540763 -2.3015387 ]
 [ 1.74481176 -0.7612069   0.3190391 ]
 [-0.24937038  1.46210794 -2.06014071]]
[[-1.07296862 -0.7612069  -2.3015387 ]
 [-0.24937038 -0.61175641 -2.06014071]
 [ 1.62434536  0.86540763 -0.52817175]
 [ 1.74481176  1.46210794  0.3190391 ]]

[[-2.3015387  -1.07296862 -0.7612069 ]
 [-2.06014071 -0.61175641 -0.24937038]
 [-0.52817175  0.86540763  1.62434536]
 [ 0.3190391 

In [156]:
mydict = {1: 'Tran A', 'chuoi': 'vang', 3.14: 'pi', "NNLT": 'python'}
mylist2 = ['a','b','c','d','e']
z = zip(mydict,mylist2)
for l1, l2 in z:
    print('key ', l1, 'co value la', mydict[l1], 'dc zip voi', l2)

key  1 co value la Tran A dc zip voi a
key  chuoi co value la vang dc zip voi b
key  3.14 co value la pi dc zip voi c
key  NNLT co value la python dc zip voi d


In [151]:
from numpy.linalg import inv
X = np.random.randn(2, 2)
mat = X.T.dot(X)
print(mat)
print(inv(mat))
print(mat.dot(inv(mat)))

[[3.76352626 0.72588267]
 [0.72588267 0.4979884 ]]
[[ 0.36962316 -0.53877369]
 [-0.53877369  2.79341141]]
[[1.00000000e+00 9.73694331e-17]
 [4.51784418e-17 1.00000000e+00]]
